# See LICENSE file in this repo for license details.

name: Scheduled Monthly

on:
  schedule:
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of the month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    # │ │ │ │ │
    # │ │ │ │ │
    # │ │ │ │ │
    # * * * * *
    - cron: "30 4 1 * *"

  # Allow triggering workflow manually
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

jobs:
  monthly:
    name: Monthly Tasks
    uses: atc0005/shared-project-resources/.github/workflows/scheduled-monthly.yml@master
    with:
      build-packages: false
      build-podman-release: false

